// Certificate of Authenticity
//
// EGP-405-01 Networking for Online Games
// Lab 2
// 7-30-2018
//
// Vedant Chaudhari, 1532077
// Lucas Spiker
// ****TODO: Finish authenticity
//
// We certify that this work is entirely our own.The assessor of this project may reproduce this project 
// and provide copies to other academic staff, and/or communicate a copy of this project to a plagiarism 
// - checking service, which may retain a copy of the project on its database.

/*
	RakNet Console Application
	Prepared by Dan Buckstein
	September 5, 2018

	Simple RakNet application following official tutorials.

	****TO-DO: add your own implementations and comments

	Resources: 
	http://www.jenkinssoftware.com/raknet/manual/tutorialsample1.html
	http://www.jenkinssoftware.com/raknet/manual/tutorialsample2.html
	http://www.jenkinssoftware.com/raknet/manual/tutorialsample3.html

	http://www.raknet.net/raknet/manual/creatingpackets.html
	http://www.raknet.net/raknet/manual/receivingpackets.html
	http://www.raknet.net/raknet/manual/sendingpackets.html
	http://www.raknet.net/raknet/manual/timestamping.html

	Read them for the secrets to success!
	E.g. pointers on pointers ;)
*/


// standard includes
#include <stdio.h>
#include <string.h>
#include <list>


// RakNet includes
#include "RakNet/MessageIdentifiers.h"
#include "RakNet/RakNetTypes.h"
#include "RakNet/RakPeerInterface.h"


enum GameMessages
{
	ID_CUSTOM_MESSAGE_START = ID_USER_PACKET_ENUM,

	ID_GAME_MESSAGE, 
	ID_CHAT_REQUEST,
	ID_CHAT_MESSAGE,
	ID_USERNAME_REQUEST,
	ID_USERNAME_MESSAGE,
	ID_USER_JOINED,
};

#pragma pack(push, 1)
struct GameMessageData
{
	unsigned char typeID;

	char message[255];
};
#pragma pack(pop)

// Generated by the client, a request for the host (server) to send out a message
#pragma pack(push, 1)
struct ChatRequest
{
	unsigned char typeID;

	char recipient[31];
	char message[511];
};
#pragma pack(pop)

// Generated by the server, a message being delivered to connected clients
#pragma pack(push, 1)
struct ChatMessage
{
	unsigned char typeID;

	bool isPrivate;

	char sender[31];
	char message[511];
};
#pragma pack(pop)

// This Structure holds the userID of all current peer connections to the server
struct userID
{
	char username[31];
	RakNet::RakNetGUID guid;
};

// entry function
int main(void)
{
	char str[512];
	bool isServer;

	unsigned int MAX_CLIENTS = 10;
	unsigned short SERVER_PORT = 60000;

	// Host Data
	std::list<userID> users;

	// Client Data
	char username[31];

	// Create RakNet peer and packet instance
	RakNet::RakPeerInterface* pPeer = RakNet::RakPeerInterface::GetInstance();
	RakNet::Packet* pPacket;

	// Ask user for peer type
	printf("(C)lient or (S)erver? \n");
	fgets(str, sizeof(str), stdin);

	// Ask user for the port
	printf("What is the server port? \n");
	scanf("%hu", &SERVER_PORT);

	// Setup Client Peer
	if ((str[0] == 'c') || (str[0] == 'C')) {
		RakNet::SocketDescriptor sd;
		pPeer->Startup(1, &sd, 1);

		isServer = false;
	}
	// Setup Host(Server) Peer
	else {
		printf("Maximum number of clients? \n");
		scanf("%d", &MAX_CLIENTS);

		RakNet::SocketDescriptor sd(SERVER_PORT, 0);
		pPeer->Startup(MAX_CLIENTS, &sd, 1);

		isServer = true;
	}

	while (1)
	{
		for (
			packet = peer->Receive(); 
			packet; 
			peer->DeallocatePacket(packet), packet = peer->Receive()
			)
		{
			switch (packet->data[0])
			{
			case ID_REMOTE_DISCONNECTION_NOTIFICATION:
			{
				printf("Another client has disconnected.\n");
				break;
			}
			case ID_REMOTE_CONNECTION_LOST:
			{
				printf("Another client has lost the connection.\n");
				break;
			}
			case ID_REMOTE_NEW_INCOMING_CONNECTION:
			{
				printf("Another client has connected.\n");
				break;
			}
			case ID_CONNECTION_REQUEST_ACCEPTED:
			{
				printf("Our connection request has been accepted.\n");
				// Send a request for our username to the server
				GameMessageData msg[1];
				msg->typeID = ID_USERNAME_REQUEST;
				strcpy(msg->message, username);

				peer->Send((char*)msg, sizeof(GameMessageData), HIGH_PRIORITY, RELIABLE_ORDERED, 0, RakNet::UNASSIGNED_RAKNET_GUID, false);
			}
			break;
			case ID_USERNAME_REQUEST:
			{
				printf("Username Request");
				// Check if a given username is available, if it is, add it to the list, otherwise send the user an error.
				GameMessageData data = *(GameMessageData*)packet->data;
				char reqUsername[31];
				GameMessageData msg[1] = { ID_USERNAME_MESSAGE };

				strcpy(reqUsername, data.message);

				bool foundDupe = false;
				for (userID currID : users)
				{
					if (strcmp(reqUsername, currID.username))
					{
						foundDupe = true;
						break;
					}
				}
				if (strcmp(reqUsername, username)) // Make sure the user isn't impersonating the server
				{
					foundDupe = true;
				}

				// If the requested username already exists.
				if (foundDupe)
				{
					strcpy(msg->message, "Username taken, please reconnect and try again.");
					peer->Send((char*)msg, sizeof(GameMessageData), HIGH_PRIORITY, RELIABLE_ORDERED, 0, RakNet::UNASSIGNED_RAKNET_GUID, false);
					peer->CloseConnection(packet->systemAddress, true);
				}
				else // If the username isn't taken.
				{
					strcpy(msg->message, "Username not taken, connection successful.");
					peer->Send((char*)msg, sizeof(GameMessageData), HIGH_PRIORITY, RELIABLE_ORDERED, 0, RakNet::UNASSIGNED_RAKNET_GUID, false);
					userID newUser;
					newUser.guid = packet->guid;
					strcpy(newUser.username, reqUsername);
					users.push_back(newUser);
				}
			}
			break;
			case ID_NEW_INCOMING_CONNECTION:
			{
				printf("A connection is incoming.\n");
				break;
			}
			case ID_NO_FREE_INCOMING_CONNECTIONS:
			{
				printf("The server is full.\n");
				break;
			}
			case ID_DISCONNECTION_NOTIFICATION:
			{
				if (isServer) {
					printf("A client has disconnected.\n");
				}
				else {
					printf("We have been disconnected.\n");
				}
				break;
			}
			case ID_CONNECTION_LOST:
			{
				if (isServer) {
					printf("A client lost the connection.\n");
				}
				else {
					printf("Connection lost.\n");
				}
				break;
			}
			case ID_GAME_MESSAGE:
			{
				printf("DEBUG MESSAGE: received packet ID_GAME_MESSAGE_1.\n");
				break;
			}
			default:
				printf("Message with identifier %i has arrived.\n", packet->data[0]);
				break;
			}
		}
	}


	// shut down networking by destroying peer interface instance
	RakNet::RakPeerInterface::DestroyInstance(peer);


	// exit
	printf("\n\n");
	system("pause");
	return 0;
}
